### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by user385** [ingles98/Bitburner-Scripts#1]
When i copy paste all 3 files and run netmap.js i get that ingame-error:

RUNTIME ERROR
netmap.js@home

Cannot read properties of undefined (reading 'apply')
stack:
TypeError: Cannot read properties of undefined (reading 'apply')
at Function.hl.use (https://unpkg.com/cytoscape@3.20.0/dist/cytoscape.esm.min.js:10:218058)
at netmap.js:38:23

**Comment by ingles98** [comment]
that is weird. will look into it
